---
? ''
: - ttl: 43200
    type: A
    values:
    - 185.199.108.153
    - 185.199.109.153
    - 185.199.110.153
    - 185.199.111.153
  - ttl: 1800
    type: MX
    values:
    - exchange: mail.casaricci.it.
      preference: 1
  - type: TXT
    values:
    - v=spf1 mx a:mail.casaricci.it include:mailgun.org -all
_autodiscover._tcp:
  type: SRV
  value:
    port: 443
    priority: 0
    target: mail.casaricci.it.
    weight: 1
_caldavs._tcp:
- ttl: 43200
  type: SRV
  value:
    port: 443
    priority: 0
    target: mail.casaricci.it.
    weight: 1
- type: TXT
  value: path=/SOGo/dav/
_carddavs._tcp:
- ttl: 43200
  type: SRV
  value:
    port: 443
    priority: 0
    target: mail.casaricci.it.
    weight: 1
- type: TXT
  value: path=/SOGo/dav/
_dmarc:
  type: TXT
  value: v=DMARC1\; p=quarantine\; rua=mailto:postmaster@casaricci.it\; fo=1\; ruf=mailto:postmaster@casaricci.it
_github-challenge-mignololab:
  type: TXT
  value: f17ca14a0b
_github-pages-challenge-mignololab:
  type: TXT
  value: de3aa3a57f7c0ad65862acb591294e
_imap._tcp:
  ttl: 43200
  type: SRV
  value:
    port: 143
    priority: 0
    target: mail.casaricci.it.
    weight: 1
_imaps._tcp:
  ttl: 43200
  type: SRV
  value:
    port: 993
    priority: 0
    target: mail.casaricci.it.
    weight: 1
_pop3._tcp:
  ttl: 43200
  type: SRV
  value:
    port: 110
    priority: 0
    target: mail.casaricci.it.
    weight: 1
_pop3s._tcp:
  ttl: 43200
  type: SRV
  value:
    port: 995
    priority: 0
    target: mail.casaricci.it.
    weight: 1
_sieve._tcp:
  ttl: 43200
  type: SRV
  value:
    port: 4190
    priority: 0
    target: mail.casaricci.it.
    weight: 1
_smtp._tls:
  type: TXT
  value: v=TLSRPTv1\; rua=mailto:postmaster@casaricci.it
_smtps._tcp:
  ttl: 43200
  type: SRV
  value:
    port: 465
    priority: 0
    target: mail.casaricci.it.
    weight: 1
_submission._tcp:
  ttl: 43200
  type: SRV
  value:
    port: 587
    priority: 0
    target: mail.casaricci.it.
    weight: 1
autoconfig:
  ttl: 43200
  type: CNAME
  value: mail.casaricci.it.
autodiscover:
  ttl: 43200
  type: CNAME
  value: mail.casaricci.it.
dkim._domainkey:
  type: TXT
  value: v=DKIM1\;k=rsa\;t=s\;s=email\;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApVanbcmMIIaUeRWkPEBYCq7vETjC8ngnpJvrpajAdcTxxl5Cmx1Fqo1gfLhwgfCNsnzMZQO/NXKYRKvGAD3WRBlxOKuSotFh9DJXcbYvGaIcenqmm9nsN4xE5zxkqV0nMBMXhHk+kx4pHNhXGRcPk1Xd8kHWlKg409eBCMPUxy0uaFPFxVrdcu/h22k+k5y6b61w/pdi6/ULGb8e4LGBi7bo9gxeN47kMtxtQhPkLDB54z64yrv8h0B85qG+U+OOTAUfIbZ9WAZuS5LCJaKnmxcNeglfeIRDb9ntZDk7NzgUWm52DH19XoFIICHqtRA1y9wpPY3Ngn1w4eQCKmn4YwIDAQAB
pic._domainkey:
  type: TXT
  value: k=rsa\; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApvIGrZUDbQ37Wl2THJZx6eujNLFikay0j+qtUvdqW6uaxDH+g626SbgvSdPS5kUfGW0F+uTSDG+7sFVEyPUHCeBB7Gm0pg2qf6Tu1WsMeki6MOY3lZxIRcZNKhwbBnkd5JSuXRKjExv7R+EGczNIQ7tqHyZB4+zma+6iXLC+W4pX3WmDgH1GpATtQ5ldzqILFNPA6Zb5bBbRxqHykWyiS0WC5fn5qWQp91tw/mhgTaRCb/OFtnluc/t2923lODM2OFPxmtsXgsKgGeFWwkG0EzujW5OHwez7yxhJs4jz20N7jDStijz1i95OkLBULtF/7W62hXqPIIAd2Ma4W/1LlwIDAQAB
www:
  ttl: 43200
  type: CNAME
  value: mignololab.github.io.
