---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config
    default_ttl: 3600
    enforce_order: True
  do:
    class: octodns_digitalocean.DigitalOceanProvider
    token: env/DIGITALOCEAN_TOKEN

zones:
  mignololab.org.:
    sources:
      - config
    targets:
      - do
...
