name: dns-sync

on:
  push:
    branches:
      - master
    paths:
      - 'config/*.yaml'
  workflow_dispatch:

env:
  DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}

jobs:
  publish:
    name: Publish DNS config
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - name: Publish
        uses: solvaholic/octodns-sync@v3
        with:
          config_path: config/production.yaml
          doit: '--doit'
